version: 2

jobs:
  build:
    docker:
      - image: quartic/uber-builder:90

    working_directory: ~/website

    steps:
      - checkout

      - restore-cache:
          keys:
            - website-v2-ssh

      - run:
          name: Register SSH key
          command: |
            if [ ! -e ~/.ssh/google_compute_engine ]; then ssh-keygen -f ~/.ssh/google_compute_engine -N ""; fi

      - save_cache:
          key: website-v2-ssh
          paths:
            - ~/.ssh

      - restore_cache:
          keys:
            - website-v2-{{ .Branch }}-yarn-{{ checksum "yarn.lock" }}
            - website-v2-{{ .Branch }}-yarn
            - website-v2-develop-yarn

      - run:
          name: Install dependencies
          command: |
            yarn install

      - save_cache:
          key: website-v2-{{ .Branch }}-yarn-{{ checksum "yarn.lock" }}
          paths:
            - node_modules

      - run:
          name: Build distribution
          command: |
            ./scripts/configure.sh
            yarn run build

      - run:
          name: Run spellchecker
          command: |
            RESULTS=$(for f in dist/*.html; do aspell list -l en_GB --add-filter=sgml --add-sgml-skip=script --add-extra-dicts=$(pwd)/wordlist < "${f}"; done)
            echo ${RESULTS}
            test "${RESULTS}" == ""

      - deploy:
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              TARGET=www.quartic.io
            elif [ "${CIRCLE_BRANCH}" == "develop" ]; then
              TARGET=www-test.quartic.io
            else
              TARGET=www-dummy.quartic.io
            fi
            gcloud-auth
            rsync -e "gcloud compute ssh --zone ${GCLOUD_ZONE} ${GCLOUD_SERVICE_ACCOUNT}@${GCLOUD_WEB_INSTANCE} -vvv --" --delete -avz dist/ :/opt/quartic/${TARGET}
