version: 2

references:

  defaults: &defaults
    working_directory: ~/website
    docker:
      - image: quartic/uber-builder:144

  gcloud_auth: &gcloud_auth
    name: GCloud auth
    command: google-cloud-auth --with-docker

  create_fallback_tag: &create_fallback_tag
    name: Create fallback tag
    command: gcloud container images add-tag ${GOOGLE_DOCKER_REPOSITORY}/website:${CIRCLE_SHA1} ${GOOGLE_DOCKER_REPOSITORY}/website:${TAG}

  deploy: &deploy
    name: Deploy to cluster
    command: kubectl set image -n www deployment/www www=${GOOGLE_DOCKER_REPOSITORY}/website:${CIRCLE_SHA1}


jobs:
  build:
    <<: *defaults

    steps:
      - checkout

      - restore_cache:
          keys:
            - website-v3-{{ .Branch }}-yarn-{{ checksum "yarn.lock" }}
            - website-v3-{{ .Branch }}-yarn
            - website-v3-develop-yarn

      - run:
          name: Install dependencies
          command: yarn install

      - save_cache:
          key: website-v3-{{ .Branch }}-yarn-{{ checksum "yarn.lock" }}
          paths:
            - node_modules

      - run:
          name: Build distribution
          command: |
            echo -e "version: ${CIRCLE_SHA1}" > src/data/build.yml
            yarn run build

      - run:
          name: Run spellchecker
          command: |
            RESULTS=$(for f in dist/*.html; do aspell list -l en_GB --add-filter=sgml --add-sgml-skip=script --add-extra-dicts=$(pwd)/wordlist < "${f}"; done)
            echo ${RESULTS}
            test "${RESULTS}" == ""

      - setup_remote_docker

      - run:
          name: Build Docker image
          command: docker build -t website .

      - run: *gcloud_auth

      - run:
          name: Push Docker image
          command: docker-tag-and-push website ${CIRCLE_SHA1}


  deploy_staging:
    <<: *defaults

    steps:
      - run: *gcloud_auth

      - run:
          <<: *create_fallback_tag
          environment:
            TAG: staging

      - run:
          name: Get cluster credentials
          command: gcloud container clusters get-credentials ${STAGING_CLUSTER_NAME} --project ${STAGING_PROJECT_ID} --zone ${STAGING_CLUSTER_ZONE}

      - deploy: *deploy


  deploy_prod:
    <<: *defaults

    steps:
      - run: *gcloud_auth

      - run:
          <<: *create_fallback_tag
          environment:
            TAG: prod

      - run:
          name: Get cluster credentials
          command: gcloud container clusters get-credentials ${PROD_CLUSTER_NAME} --project ${PROD_PROJECT_ID} --zone ${PROD_CLUSTER_ZONE}

      - deploy: *deploy


workflows:
  version: 2

  build_and_deploy:
    jobs:
      - build

      - hold:
          type: approval
          requires:
            - build

      - deploy_staging:
          requires:
            - hold


      # - deploy_staging:
      #     requires:
      #       - build
      #     filters:
      #       branches:
      #         only: develop

      # - hold:
      #     type: approval
      #     requires:
      #       - deploy_staging
      #     filters:
      #       branches:
      #         only: develop

      # - deploy_prod:
      #     requires:
      #       - hold
      #     filters:
      #       branches:
      #         only: develop
